name: Java Maven CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      # Step 3: Build using Maven
      - name: Build with Maven
        run: mvn clean compile


      # step 4: Test using Maven
      - name: package the application
        run: mvn clean package -DskipTests


      # Step 5: Upload build artifact (Deploy stage example)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworldweb-artifact
          path: target/*.war



  package-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4
      # step 2: Test using Maven
      - name: package the application
        run: mvn clean package -DskipTests
      # Step 3: Upload build artifact (Deploy stage example)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworldweb-artifact
          path: target/*.war
